---
- name: Nginx в Docker
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: pip для Python
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: docker для Python
      ansible.builtin.pip:
        name: docker
        state: present
        extra_args: --break-system-packages

    - name: Nginx запускаем контейнер
      community.docker.docker_container:
        name: my_nginx_server
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80"
        volumes:
          - "/home/elistan/MyLabiry/website:/usr/share/nginx/html:ro"
