---
# Три тире выше — это обязательное начало любого YAML-файла

- name: Топовое развертывание веб-сервера Nginx в Docker  # Название всего плейбука (для логов)
  hosts: localhost                                        # Запускаем локально на нашей Kali Linux
  connection: local                                       # Подключаемся без SSH, напрямую к себе
  become: true                                            # Запуск от root (sudo), так как Docker требует прав

  tasks: # Секция, где по очереди выполняются все наши шаги (таски)

    - name: 1. Проверяем, что пакет pip для Python установлен
      ansible.builtin.apt:                                # Модуль apt для управления пакетами в Kali/Ubuntu
        name: python3-pip                                 # Имя пакета, который нам нужен
        state: present                                    # present значит "убедись, что он установлен"  

    - name: 2. Устанавливаем библиотеку docker для Python
      ansible.builtin.pip:                                # Модуль pip (ставит модули для Python)
        name: docker                                      # Без этой библиотеки Ansible не сможет управлять Докером
        state: present                                    # Проверяет: если уже есть — пропустит, если нет — поставит
        extra_args: --break-system-packages   
  
    - name: 3. Скачиваем официальный образ Nginx и запускаем контейнер
      community.docker.docker_container:                  # Специальный крутой модуль Ansible для работы с Docker
        name: my_nginx_server                             # Как будет называться наш контейнер в списке "docker ps"
        image: nginx:latest                               # Какой образ скачать с Docker Hub (берем самый свежий)
        state: started                                    # Контейнер должен быть запущен (если за стоплен — Ansible его включит)
        restart_policy: always                            # Если виртуалка перезагрузится, Docker сам поднимет этот контейнер
        
        ports:                                            # Секция проброса портов (Внешний_порт : Внутренний_порт)
          - "8080:80"                                     # Стучимся на Kali по порту 8080 ➡️ попадаем внутрь контейнера на порт 80

        volumes:                                          # Секция монтирования папок (Папка_на_Kali : Папка_в_контейнере)
          - "/home/elistan/MyLabiry/website:/usr/share/nginx/html:ro" 
          # Выше: Папку с нашим сайтом на Kali мы прокидываем внутрь Nginx. 
          # ":ro" означает Read-Only (контейнер может только читать наши файлы, но не удалит их).
